### PR TITLE
Use libtorrent 2.0 for release building

### PR DESCRIPTION
**Pull request by abcfy2**
Seems that libtorrent 2.0 is working now. So switch libtorrent 2.0 for release building.

### CODE REVIEW

**Comment by c0re100** [comment]
As I said before, libtorrent 2.0 is not fully supported, this PR should be belong v4.4 branch.

**Comment by c0re100** [comment]
4.4.0 Beta1 is out~
so I've created v4_4_x branch, and I will apply enhanced patch to v4_4_x tomorrow.
Can you rebase commit on v4_4_x branch?
Thanks.

**Comment by abcfy2** [comment]
Sure. I will test if it's still working for new branch. After that, I will create a new PR for new branch.

**Comment by abcfy2** [comment]
New PR created #270 . So close this PR.

**Pull request closed without merging**
