### PR TITLE
Fix arguments handling in "Run external program on torrent completion"

### PR DESCRIPTION
**Pull request by fitu996**
I just want a torrent client that will handle argument correctly and safely. However, upstream seems not interested in my patch. 

## More information:

[https://github.com/qbittorrent/qBittorrent/pull/12392](https://github.com/qbittorrent/qBittorrent/pull/12392)

[https://github.com/qbittorrent/qBittorrent/issues/12367](https://github.com/qbittorrent/qBittorrent/issues/12367)

### CODE REVIEW

**Comment by c0re100** [comment]
I don't have time till 1/5. So plesae wait.....:(

**Comment by c0re100** [comment]
Can anyone provide me a test case for testing this PR?

**Comment by fitu996** [comment]
For windows? Or linux?

Linux test case is here \(at `Steps to reproduce` part\): https://github.com/qbittorrent/qBittorrent/issues/12367

**Comment by c0re100** [comment]
> For windows? Or linux?
> 
> Linux test case is here (at `Steps to reproduce` part): [qbittorrent#12367](https://github.com/qbittorrent/qBittorrent/issues/12367)

For windows.

**Comment by fitu996** [comment]
Windows is untouched because it seems that arguments handling is wrong only in unix-like OS.

**Comment by c0re100** [comment]
Thanks.

**Pull request merged**
